### PR TITLE
Add support for chacha20-poly1305@openssh.com, ssh-ed25519, ssh-ed448, curve448-sha512, diffie-hellman-group15-sha512 & diffie-hellman-group17-sha512

### PR DESCRIPTION
**Pull request by norrisjeremy**
This makes use of the new EdDSA feature added in [Java 15's JEP 339](https://openjdk.java.net/jeps/339).
I also tweaked the Github workflow to hopefully:
1. Run tests against Java 8, 11 & 15.
2. Cache local maven repository to speed up builds a bit.
3. Archive entire set of Surefire, Failsafe & JaCoCo reports.

I ran tests locally for a couple hours last night and didn't see any failures, so hopefully there aren't any bugs in the new EdDSA code.

### CODE REVIEW

**Comment by norrisjeremy** [comment]
Not sure why the CI build is hung? It seems everything built successfully.

**Comment by norrisjeremy** [comment]
FYI, I _think_ that I have also put together implementations of curve448-sha512 & ssh-ed448 that could be ready soon.
I'm going to let integration tests run in a loop for a few hours to confirm.

**Comment by norrisjeremy** [comment]
FYI, I ran torture tests repeatedly of all the curve25519-sha256, curve448-sha512, ssh-ed25519 & ssh-ed448 this evening and didn't encounter any failures:
```
for i in $(jot 100); do
  tools/bin/gen-ed448-keys.py
  echo yes | ssh-keygen -t ed25519 -N '' -f id_ed25519 -C test >/dev/null
  echo yes | ssh-keygen -t ed25519 -N '' -f ssh_host_ed25519_key -C test >/dev/null
  echo yes | ssh-keygen -t rsa -N '' -f id_rsa -C test >/dev/null
  echo yes | ssh-keygen -t rsa -N '' -f ssh_host_rsa_key -C test >/dev/null
  chmod 644 id_ed* ssh_host_ed* id_rsa* ssh_host_rsa*
  cat id_ed*.pub id_rsa*.pub >src/test/resources/docker/authorized_keys
  mv id_ed* ssh_host_ed* id_rsa* ssh_host_rsa* src/test/resources/docker/
  mvn verify -DskipITs=false -Dit.test=AlgorithmsIT#testJava11KEXs+testEd25519,Algorithms2IT#testKEXs,testEd448
done
```

FYI, I purposely didn't enable curve448-sha512 & ssh-ed448 by default in the in JSch's config, since neither algorithm is supported yet by OpenSSH.

**Comment by norrisjeremy** [comment]
With having AsyncSSH hooked into the integration tests, it was pretty easy to add support for diffie-hellman-group15-sha512 & diffie-hellman-group17-sha512.
I left them both disabled by default in the in JSch's config, since neither algorithm is supported by OpenSSH.

**Comment by norrisjeremy** [comment]
Adding support for [chacha20-poly1305@openssh.com](https://cvsweb.openbsd.org/src/usr.bin/ssh/PROTOCOL.chacha20poly1305?annotate=HEAD) a bit tricky.
It turns out that using `Cipher.getInstance("ChaCha20-Poly1305")` won't work, as the way OpenSSH combines together ChaCha20 + Poly1305 isn't done in the same way specified in RFC 7539.
Java also doesn't seem to allow instantiating a standalone instance of Poly1305 MAC either.
So I found a standalone Poly1305 implementation within the [OpenJAX project](https://github.com/openjax/security) that is [MIT licensed](http://opensource.org/licenses/MIT/), which I combined with the [JEP 329](https://openjdk.java.net/jeps/329) implementation of `Cipher.getInstance("ChaCha20")`.
I also wrote some unit tests for this Poly1305 implementation using test vectors specified in RFC 7539 and from the [BoringSSL project](https://boringssl.googlesource.com/boringssl/+/refs/heads/master/crypto/poly1305/poly1305_tests.txt).

**Comment by norrisjeremy** [comment]
I forgot to mention: I also torture tested the `chacha20-poly1305@openssh.com` locally by executing `for i in $(jot 100); do mvn verify -DskipITs=false -Dit.test=AlgorithmsIT#testJava11Ciphers; done` and didn't see any failures.

**Comment by mwiede** [comment]
> Not sure why the CI build is hung? It seems everything built successfully.

The problem was the github branch configuration. Since we use matrix build, the name of the required check has changed. now showing `Passed`

**Pull request merged**
