### PR TITLE
Several updates

### PR DESCRIPTION
**Pull request by norrisjeremy**
1. Reduce number of algorithms that are runtime checked to improve baseline performance (came up in #47).
2. Add system properties to allow overriding the default crypto algorithms used (in response to #59).
3. Switch from PubkeyAcceptedKeyTypes to PubkeyAcceptedAlgorithms to match recent changes in OpenSSH.
4. Prefer ssh-ed25519 to match recent changes in OpenSSH.
5. Allow configuration of DHGEX sizes and align the default sizes with recommendations from RFC-8270.
6. Directly import JZlib since it appears unmaintained upstream.
7. Add license files for OpenJAX & jBCrypt.
8. Update dependencies to latest versions.
9. Switch Github CI from Java 15 to Java 16 since that is current version of OpenJDK.
10. Modularize jarfile.
11. Mark a few classes package private that are not intended to be public.

### CODE REVIEW

**Comment by norrisjeremy** [comment]
FYI, with the Github CI change from Java 15 to 16, the CI checks above probably will hang until you update the project to expect them from Java 16.

Also,  when I was sweeping through dependency updates, I wasn't sure if the `wagon-ssh-external` extension should be updated to a newer version? The version specified in `pom.xml` appears to be quite old.

**Comment by mwiede** [comment]
@norrisjeremy can you please update the Readme of the frontpage with some information on system properties, so that users know, what to to do in order to configure old algorithms/old behavior? Thanks for your contribution!

**Comment by norrisjeremy** [comment]
Yep, I'll update the Readme later today or over the weekend and push an update to this PR.

**Comment by norrisjeremy** [comment]
Let me know if the changes to the Readme look ok, or if you would like additional changes.

**Pull request merged**
